language: node_js
node_js:
- stable
sudo: false
cache:
  directories:
  - node_modules
script: make test-all
env:
  global:
  - secure: DB1e9naCtikmO9l89TLK0eplmoFPGzPpbV4Y+pVNyNLwtt23ozK+eDeUb8s9f6Mt/AJqq8Jb8GvxWFYjGbJb6IhXFhndRGP6pt2rqBMSpiY4aIwUWHSZZlnSF4Mvo5P6I22u/uHh3Gy2i/CtlG/D2wg8qHBkdkk4eklneHa6A8Y=
  - secure: eLYuCLKTzL2G0JunrSTJg79cXn/oxIaie+A1CAMrAxhwKRYS/KI1WJcdpyX4kXATTl0spOT/qHaN0PIydzIokZH8AoD++Mbi3CMGUasBhw2/akDXf2/m0tZew5p2OUs+5pG4lzJYjpXf9lJ1Ok2FD3yUwCiq5zMRn2+Qv8J6/lA=
