sudo: required
language: node_js
matrix:
  fast_finish: true
  include:
  - node_js: '8'
    env: TASK=browser
  - node_js: '8'
    env: TASK=coveralls
  - node_js: '10'
    env: TASK=unit
  - node_js: '6'
    env: TASK=unit
cache:
  directories:
  - node_modules
script:
- make ${TASK}
env:
  global:
    # travis encrypt SAUCE_USERNAME=spipe --add
  - secure: RK2BBNk8WLs2AZCo3rcycxyWa21phVrL9dT7Oh8DaLNJtgpAduZ5msxKfsUmoi4td18BzRUXs4gp+kDUPJXUeRLPvrvxd77JLft7dYSsSICY+poj5hDynUUB5MW+Pwkib/kL6A1OE1gLaC1/SJP7zmvHo4stLl7D914CPDE9r7E=
  - secure: GvaYZVIzOpB9EiJMFxLkuRPC7Kz+ZiKaHuyeC6dmN+x9ubgQj0fBVAvA4nraPSHjB97PFnHOk/cQhB/1ZkSmjETtQPQEFzEn5a0t14iqNRm5tHL8UNEVCAx7LccUAWR1SuWJd4s193PgCWPbAD69ecU3/N1TErNiIQrhUJmmvGA=
