ui: mocha-bdd
concurrency: 5
browsers:
  - name: android
    version: [oldest, latest]
  - name: chrome
    version: [oldest, latest]
  - name: firefox
    version: [oldest, latest]
  - name: ie
    version: oldest..latest
  - name: iphone
    version: [5.1, 6.0, 9.2]
  - name: safari
    version: oldest..latest
