ui: mocha-bdd
concurrency: 5
browsers:
  - name: android
    version: [oldest, latest]
  - name: chrome
    version: [oldest, latest]
  - name: firefox
    version: [oldest, latest]
  - name: ie
    version: oldest..latest
  - name: iphone
    version: [6.0, latest]
  - name: opera
    version: oldest..latest
  - name: safari
    version: oldest..latest
