ui: mocha-bdd
concurrency: 1
browsers:
  - name: chrome
    version: 45
  - name: ie
    version: 10..11
  - name: firefox
    version: 41
  - name: iphone
    version: 9.1
  - name: ipad
    version: 9.1
  - name: android
    version: 5.1
  - name: opera
    version: 12
  - name: safari
    version: 8.1
