ui: mocha-bdd
concurrency: 5
browsers:
  - name: android
    version: [4.4, 5.1]
  - name: chrome
    version: [oldest, latest]
  - name: firefox
    version: [oldest, latest]
  - name: ie
    version: oldest..latest
  - name: iphone
    version: [oldest, latest]
  - name: safari
    version: oldest..latest
  - name: microsoftedge
    version: [oldest, latest]
  - name: opera
    version: [11, 12]
